### ISSUE TITLE
Add rss [id] command

### ISSUE THREAD

**Issue by ryusamii** [devCelKyo/Ramen-Simulator#6]
With "rss [ID]" you can see a restaurant's information using its unique ID.

**Comment by devCelKyo** [comment]
Looking into it https://github.com/devCelKyo/Ramen-Simulator/commit/dcc610680ba407c07cf32a2d24550ec647d9f456

**Comment by devCelKyo** [comment]
Done. https://github.com/devCelKyo/Ramen-Simulator/commit/c6b275ef7fe65958cdf68f63e2f0ecc966af7c16
